# Generated by Django 5.2.4 on 2025-08-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_aboutsection_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('icon', models.CharField(choices=[('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('email', 'Email'), ('twitter', 'Twitter'), ('facebook', 'Facebook'), ('custom', 'Custom')], default='custom', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
