# Generated by Django 5.2.4 on 2025-08-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_footerlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default='SRA Portfolio', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Portfolio', max_length=100)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='favicon/')),
            ],
        ),
    ]
