# Generated by Django 5.2.9 on 2025-12-29 17:52

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homesection',
            name='resume_file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='resume/'),
        ),
    ]
